### ISSUE TITLE
[1.18.2] Debugify 1.10.0 causes client crash

### ISSUE THREAD

**Issue by gchpaco** [W-OVERFLOW/Debugify#85] opened 2022-05-08 00:41 UTC
### Bug Description

When attempting to load with Debugify 1.10.0, my client dies.  This does not happen with 1.9.0.

### How to Reproduce?

Upgrade to 1.10.0, and launch client.

### Expected Behavior

Expected Minecraft to launch successfully.

### Version

1.10.0

### Mod Loader Version

1.18.2 - 40.1.16

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/gchpaco/e52ce9040b05572b467be97f12425158

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by border999** [comment] 2022-05-08 00:45
https://github.com/W-OVERFLOW/Debugify/issues/84 just reported this

**Comment by isXander** [comment] 2022-05-08 07:10
Duplicate of #84

**Closed by isXander** 2022-05-08 07:10 UTC
Labels: bug
