### ISSUE TITLE
[Bug] Breaks a bunch of mixins

### ISSUE THREAD

**Issue by freopt** [W-OVERFLOW/Debugify#68] opened 2022-04-18 20:58 UTC
**Describe the bug**
When newest forge version of mod is used it breaks a ton of forge mixins

**Desktop (please complete the following information):**
 - Minecraft Version: 1.18.2
 - Mod Loader: Forge 40.0.54 
 - Mod Version: `1.2.0`
[latest.log](https://github.com/W-OVERFLOW/Debugify/files/8508133/latest.log)
I know debugify isn't mentioned in the error but if I remove it the game launches fine whereas if I remove ferritecore then 
ftblib mixin errors and then kubejs

**Comment by freopt** [comment] 2022-04-18 20:59
It seems like https://github.com/W-OVERFLOW/Debugify/issues/66 is the same thing but that's fabric and this is forge so I'll leave this here

**Comment by isXander** [comment] 2022-04-18 21:02
Duplicate of #66

**Closed by isXander** 2022-04-18 21:02 UTC
Labels: bug, duplicate
